# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
    branches:
      - develop
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
      - name: Preparing environment
        id: setup_environment
        run: npm install -g yarn
      - name: Installing modules
        id: install_modules
        run: |
          yarn cache clean
          rm -rf node_modules
          yarn install
      - name: Running tests
        id: tests
        run: yarn test:ci
      - name: Build test
        id: build_test
        run: yarn build:test
      - name: Publish to Chromatic
        id: chromatic_publish
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
      - name: Slack notification
        uses: Foxhoundn/slack@v1.2.94
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: ReQore Tests
